float4 main(float4 p : POSITION,
            float4 c0 : COLOR0,
            float4 t0 : TEXCOORD0,
            float4 t1 : TEXCOORD1,
            float4 t2 : TEXCOORD2,
            float4 t3 : TEXCOORD3,
            float4 t4 : TEXCOORD4,
#ifdef TEST_SECONDARY
            float4 c1 : COLOR1) : COLOR
{
    return p + c0 + c1 + t0 + t1 + t2 + t3 + t4;
#else
            float4 t5 : TEXCOORD5) : COLOR
{
    return p + c0 + t0 + t1 + t2 + t3 + t4 + t5;
#endif
}
