# Capture before/after compiler behavior without normalizing diagnostics.
# Required: CGC, SOURCE_DIR, OUTPUT_DIR. Optional: COMPARE_DIR.
foreach(arg CGC SOURCE_DIR OUTPUT_DIR)
    if(NOT DEFINED ${arg} OR "${${arg}}" STREQUAL "")
        message(FATAL_ERROR "${arg} is required")
    endif()
endforeach()
if(DEFINED COMPARE_DIR AND "${COMPARE_DIR}" STREQUAL "${OUTPUT_DIR}")
    message(FATAL_ERROR "Comparison and output directories must differ")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
foreach(shader position reflection vertexlight vertexlight4)
    foreach(version 1.1 2.0)
        set(name "${shader}-${version}")
        execute_process(COMMAND "${CGC}" -quiet -version "${version}"
            -profile generic "${SOURCE_DIR}/${shader}.cg"
            RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
        if(NOT "${status}" MATCHES "^-?[0-9]+$")
            message(FATAL_ERROR "Could not execute compiler: ${status}")
        endif()
        foreach(stream stdout stderr status)
            string(REPLACE "\r\n" "\n" value "${${stream}}")
            file(WRITE "${OUTPUT_DIR}/${name}.${stream}" "${value}")
            if(DEFINED COMPARE_DIR)
                set(reference "${COMPARE_DIR}/${name}.${stream}")
                if(NOT EXISTS "${reference}")
                    message(FATAL_ERROR "Missing baseline: ${reference}")
                endif()
                file(READ "${reference}" expected)
                string(REPLACE "\r\n" "\n" expected "${expected}")
                if(NOT "${value}" STREQUAL "${expected}")
                    message(FATAL_ERROR "Baseline differs: ${name}.${stream}")
                endif()
            endif()
        endforeach()
        message(STATUS "${name}: ${status}")
    endforeach()
endforeach()
