file(READ "${SOURCE_ROOT}/CMakeLists.txt" build)
if(NOT build MATCHES "\\$\\{CGC_MSL_LOWER_SOURCES\\}" OR
   NOT build MATCHES "get_target_property\\(CGC_MSL_FAULT_SOURCES cgc SOURCES\\)" OR
   NOT build MATCHES "add_executable\\(cgc_msl_fault \\$\\{CGC_MSL_FAULT_SOURCES\\}\\)")
    message(FATAL_ERROR "Production and failure-injection targets must share real sources")
endif()
function(check_text text output)
    if(text MATCHES "#include[ \t]+\"(glsl|hlsl|arb)[^\"]*\"" OR
       text MATCHES "(^|[^A-Za-z0-9_])(expr|stmt)[ \t]*\\*" OR
       text MATCHES "(->|\\.)(un|bin|tri)\\.")
        set(${output} FALSE PARENT_SCOPE)
    else()
        set(${output} TRUE PARENT_SCOPE)
    endif()
endfunction()
file(GLOB sources "${SOURCE_ROOT}/msl_lower*.c" "${SOURCE_ROOT}/msl_bind.c" "${SOURCE_ROOT}/msl_codegen.c")
foreach(source IN LISTS sources)
    file(READ "${source}" content)
    check_text("${content}" valid)
    if(NOT valid)
        message(FATAL_ERROR "Forbidden frontend traversal or backend dependency: ${source}")
    endif()
endforeach()
foreach(specimen "#include \"glsl_ir.h\"" "expr *tree" "stmt *body" "tree->bin.left")
    check_text("${specimen}" valid)
    if(valid)
        message(FATAL_ERROR "Structure check missed deliberate invalid specimen")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/cg_ir.h" ir)
file(READ "${SOURCE_ROOT}/msl_lower_expr.c" expressions)
file(READ "${SOURCE_ROOT}/msl_lower_stmt.c" statements)
string(REGEX MATCHALL "CGIR_EXPR_[A-Z_]+" expr_kinds "${ir}")
string(REGEX MATCHALL "CGIR_STMT_[A-Z_]+" stmt_kinds "${ir}")
list(REMOVE_DUPLICATES expr_kinds)
list(REMOVE_DUPLICATES stmt_kinds)
foreach(kind IN LISTS expr_kinds)
    if(NOT expressions MATCHES "case ${kind}:" AND NOT kind STREQUAL "CGIR_EXPR_INTERFACE_CALL")
        message(FATAL_ERROR "Uninventoried source expression: ${kind}")
    endif()
endforeach()
foreach(kind IN LISTS stmt_kinds)
    if(NOT statements MATCHES "case ${kind}:" AND NOT kind MATCHES "^CGIR_STMT_GEOMETRY_(EMIT|FLAT|RESTART)$")
        message(FATAL_ERROR "Uninventoried source statement: ${kind}")
    endif()
endforeach()
# Interface calls and geometry statements intentionally reach located C6602/
# C6606 rejection. New enum values cannot silently inherit that exception.
