cmake_minimum_required(VERSION 3.16)
if(NOT DEFINED SOURCE_ROOT OR NOT DEFINED STRUCTURE_SCRIPT)
    message(FATAL_ERROR "SOURCE_ROOT and STRUCTURE_SCRIPT required")
endif()
set(fixture "${SOURCE_ROOT}/build-cg20-arb-structure-fixture")
file(MAKE_DIRECTORY "${fixture}/tests" "${fixture}/.worktrees/other")
file(WRITE "${fixture}/.worktrees/other/copy.c" "")
file(WRITE "${fixture}/unrelated.c" "")
file(WRITE "${fixture}/tests/stub.c" "")
file(WRITE "${fixture}/arb_lower_internal.h" "")
set(root_cmake [=[set(CGC_ARB_LOWER_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/arb_lower.c
    ${CMAKE_CURRENT_SOURCE_DIR}/arb_lower_support.c
    ${CMAKE_CURRENT_SOURCE_DIR}/arb_lower_operand.c
    ${CMAKE_CURRENT_SOURCE_DIR}/arb_lower_expr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/arb_lower_loop.c
    ${CMAKE_CURRENT_SOURCE_DIR}/arb_lower_stmt.c
)
add_executable(cgc ${CGC_ARB_LOWER_SOURCES})
]=])
file(WRITE "${fixture}/CMakeLists.txt" "${root_cmake}")
file(WRITE "${fixture}/tests/CMakeLists.txt" [=[]=])
file(WRITE "${fixture}/arb_lower.c" [=[#include "arb_lower_internal.h"
int ArbLowerProgram(void) { return 0; }
]=])
file(WRITE "${fixture}/arb_lower_support.c" "#include \"arb_lower_internal.h\"\n")
file(WRITE "${fixture}/arb_lower_operand.c" "#include \"arb_lower_internal.h\"\n")
file(WRITE "${fixture}/arb_lower_expr.c" "#include \"arb_lower_internal.h\"\n")
file(WRITE "${fixture}/arb_lower_loop.c" "#include \"arb_lower_internal.h\"\n")
file(WRITE "${fixture}/arb_lower_stmt.c" "#include \"arb_lower_internal.h\"\n")
function(Check expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_ROOT=${fixture}" -P "${STRUCTURE_SCRIPT}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "PASS")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${output}${error}")
        endif()
    else()
        string(FIND "${output}${error}" "${expected}" found)
        if(result EQUAL 0 OR found LESS 0)
            message(FATAL_ERROR "wrong failure: ${output}${error}")
        endif()
    endif()
endfunction()
Check("PASS")
file(WRITE "${fixture}/unrelated.c" "#include \"arb_lower_internal.h\"\n")
Check("outside the lowering")
file(WRITE "${fixture}/unrelated.c" "int ArbLowerProgram(void) { return 0; }\n")
Check("only arb_lower.c may define it")
file(WRITE "${fixture}/unrelated.c" "")
file(WRITE "${fixture}/tests/stub.c" "#include \"arb_lower_internal.h\"\n")
Check("outside the lowering")
file(WRITE "${fixture}/tests/stub.c" "int ArbLowerProgram(void) { return 0; }\n")
Check("PASS")
file(WRITE "${fixture}/.worktrees/other/copy.c" [=[#include "arb_lower_internal.h"
int ArbLowerProgram(void) { return 0; }
]=])
Check("PASS")
string(REPLACE "arb_lower_support.c" "arb_lower.c" duplicate "${root_cmake}")
file(WRITE "${fixture}/CMakeLists.txt" "${duplicate}")
Check("exactly once")
string(REPLACE "\${CMAKE_CURRENT_SOURCE_DIR}/" "\${CMAKE_CURRENT_SOURCE_DIR}/wrong/" wrong "${root_cmake}")
file(WRITE "${fixture}/CMakeLists.txt" "${wrong}")
Check("exactly once")
string(REPLACE "add_executable(cgc " "add_executable(cgc arb_lower.c " bypass "${root_cmake}")
file(WRITE "${fixture}/CMakeLists.txt" "${bypass}")
Check("directly lists")
file(WRITE "${fixture}/CMakeLists.txt" "${root_cmake}")
file(WRITE "${fixture}/arb_lower_support.c" "")
Check("must include")
file(WRITE "${fixture}/arb_lower_support.c" "#include \"arb_lower_internal.h\"\n")
Check("PASS")
