foreach(required REQUIRED ACTUAL)
    if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
        message(FATAL_ERROR "${required} inventory is missing: ${${required}}")
    endif()
endforeach()

file(STRINGS "${REQUIRED}" required_cases)
file(STRINGS "${ACTUAL}" actual_cases)
list(FILTER required_cases EXCLUDE REGEX "^[ 	]*(#|$)")
list(FILTER actual_cases INCLUDE REGEX
    "[|]hlsl(v|g|f)(40|50)[|]")

set(seen_names)
set(seen_combinations)
foreach(case IN LISTS required_cases)
    if(NOT case MATCHES
       "^([^|]+)[|](hlsl(v|g|f)(40|50))[|]([^|]+)[|]([^|]*)[|]([^|]*)[|]([^|]*)[|]([^|]*)$")
        message(FATAL_ERROR "malformed required modern FXC case: ${case}")
    endif()
    set(case_name "${CMAKE_MATCH_1}")
    set(combination
        "${CMAKE_MATCH_2}|${CMAKE_MATCH_5}|${CMAKE_MATCH_6}|${CMAKE_MATCH_7}|${CMAKE_MATCH_8}|${CMAKE_MATCH_9}")
    list(FIND seen_names "${case_name}" name_index)
    if(NOT name_index EQUAL -1)
        message(FATAL_ERROR
            "duplicate required modern FXC test name: ${case_name}")
    endif()
    list(APPEND seen_names "${case_name}")
    list(FIND seen_combinations "${combination}" combination_index)
    if(NOT combination_index EQUAL -1)
        message(FATAL_ERROR
            "duplicate required modern FXC combination: ${combination}")
    endif()
    list(APPEND seen_combinations "${combination}")
endforeach()

list(SORT required_cases)
list(REMOVE_DUPLICATES required_cases)
list(SORT actual_cases)
list(REMOVE_DUPLICATES actual_cases)
if(NOT actual_cases STREQUAL required_cases)
    foreach(required_case IN LISTS required_cases)
        list(FIND actual_cases "${required_case}" actual_index)
        if(actual_index EQUAL -1)
            message(STATUS "missing modern FXC validation: ${required_case}")
        endif()
    endforeach()
    foreach(actual_case IN LISTS actual_cases)
        list(FIND required_cases "${actual_case}" required_index)
        if(required_index EQUAL -1)
            message(STATUS "untracked modern FXC validation: ${actual_case}")
        endif()
    endforeach()
    message(FATAL_ERROR
        "modern FXC validation inventory differs from the successful-fixture contract")
endif()

list(LENGTH required_cases required_count)
if(required_count LESS 1)
    message(FATAL_ERROR "modern FXC validation inventory is empty")
endif()
message(STATUS "modern FXC coverage: ${required_count} exact combinations")
