# Each registered test owns this directory; discard evidence from an earlier
# deliberately crashed run before checking newly leaked temporary files.
file(GLOB old_temps "${WORK_DIR}/*.cgc-tmp-*")
if(old_temps)
    file(REMOVE ${old_temps})
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")
set(output "${WORK_DIR}/shader.metal")
# The first successful allocation index proves that all earlier allocation
# sites in both scratch validation and generation have been exercised.
set(succeeded FALSE)
foreach(index RANGE 0 12000)
    file(WRITE "${output}" "KEEP_EXISTING_OUTPUT")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env ASAN_OPTIONS=detect_leaks=0 "CGC_TEST_MSL_FAIL_AT=${index}"
        "${CGC}" -quiet -version 2.0 -profile "${PROFILE}" -o "${output}" "${SOURCE}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(READ "${output}" actual)
    if("${status}" STREQUAL "0")
        if(NOT actual MATCHES "cgc-msl-abi")
            message(FATAL_ERROR "False success after allocation ${index}")
        endif()
        set(succeeded TRUE)
        set(allocation_count "${index}")
        break()
    endif()
    if(NOT "${status}" MATCHES "^[1-9][0-9]*$" OR
       NOT "${out}${err}" MATCHES "Metal allocation failure" OR
       NOT actual STREQUAL "KEEP_EXISTING_OUTPUT")
        message(FATAL_ERROR "Fault ${index}: ${status}\n${out}${err}\n${actual}")
    endif()
    file(GLOB leaked "${WORK_DIR}/*tmp*" "${WORK_DIR}/.*tmp*")
    if(leaked)
        message(FATAL_ERROR "Fault ${index} leaked ${leaked}")
    endif()
endforeach()
if(NOT succeeded)
    message(FATAL_ERROR "Fault sweep did not reach the success boundary")
endif()
message(STATUS "Verified ${allocation_count} allocation failure points")
file(WRITE "${WORK_DIR}/allocations.txt" "${allocation_count}\n")
foreach(existing YES NO)
    file(REMOVE "${output}")
    if(existing)
        file(WRITE "${output}" "KEEP_EXISTING_OUTPUT")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env ASAN_OPTIONS=detect_leaks=0 CGC_TEST_MSL_WRITER_FAIL=1
        "${CGC}" -quiet -version 2.0 -profile "${PROFILE}" -o "${output}" "${SOURCE}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if("${status}" STREQUAL "0")
        message(FATAL_ERROR "Injected writer failure reported success")
    endif()
    if(existing)
        file(READ "${output}" actual)
        if(NOT actual STREQUAL "KEEP_EXISTING_OUTPUT")
            message(FATAL_ERROR "Writer failure replaced existing output")
        endif()
    elseif(EXISTS "${output}")
        message(FATAL_ERROR "Writer failure installed partial output")
    endif()
endforeach()
