file(MAKE_DIRECTORY "${WORK_DIR}")
get_filename_component(source_name "${SOURCE}" NAME)
foreach(mode code nocode)
    set(extra)
    if(mode STREQUAL "nocode")
        set(extra -nocode)
    endif()
    foreach(existing YES NO)
        set(output "${WORK_DIR}/shader.metal")
        file(REMOVE "${output}")
        if(existing)
            file(WRITE "${output}" "KEEP_EXISTING_OUTPUT")
        endif()
        execute_process(COMMAND "${CGC}" -quiet -version 2.0 -profile "${PROFILE}"
            ${extra} -o "${output}" "${SOURCE}"
            RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
        set(log "${out}${err}")
        file(WRITE "${WORK_DIR}/${mode}-${existing}.log" "${status}\n${log}")
        if("${status}" STREQUAL "0" OR NOT log MATCHES "${REJECT}" OR
           NOT log MATCHES "${source_name}\\(${REJECT_LINE}\\)" OR
           log MATCHES "cgc-msl-abi|#include <metal_stdlib>")
            message(FATAL_ERROR "Expected located ${REJECT} (${mode}): ${status}\n${log}")
        endif()
        if(existing)
            file(READ "${output}" contents)
            if(NOT contents STREQUAL "KEEP_EXISTING_OUTPUT")
                message(FATAL_ERROR "Failed compile changed existing output")
            endif()
        elseif(EXISTS "${output}")
            message(FATAL_ERROR "Failed compile installed output")
        endif()
        file(GLOB leaked "${WORK_DIR}/*tmp*" "${WORK_DIR}/.*tmp*")
        if(leaked)
            message(FATAL_ERROR "Leaked temporary outputs: ${leaked}")
        endif()
    endforeach()
endforeach()

execute_process(COMMAND "${CGC}" -quiet -version 2.0 -profile "${PROFILE}" "${SOURCE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if("${status}" STREQUAL "0" OR NOT "${out}${err}" MATCHES "${REJECT}" OR out MATCHES "cgc-msl|metal_stdlib")
    message(FATAL_ERROR "Rejected stdout installed target text: ${out}${err}")
endif()
