function(read_case name output)
    file(READ "${BASE_DIR}/coverage-${name}/shader.metal" text)
    set(${output} "${text}" PARENT_SCOPE)
endfunction()
function(require_record text record)
    string(FIND "${text}" "// ${record}\n" found)
    if(found LESS 0)
        message(FATAL_ERROR "Missing exact ABI record: ${record}")
    endif()
endfunction()
foreach(pair order resources attributes)
    read_case(metadata_${pair}_a a)
    read_case(metadata_${pair}_b b)
    string(REGEX MATCHALL "// cgc-msl-[^\n]+" a_records "${a}")
    string(REGEX MATCHALL "// cgc-msl-[^\n]+" b_records "${b}")
    if(NOT "${a_records}" STREQUAL "${b_records}")
        message(FATAL_ERROR "Reordering declarations changed ${pair} ABI records:\n${a_records}\n${b_records}")
    endif()
endforeach()
read_case(metadata_order_a text)
require_record("${text}" "cgc-msl-buffer index=0 bytes=48 alignment=16")
require_record("${text}" "cgc-msl-uniform path=a offset=0 slots=1 type=float wire=float4")
require_record("${text}" "cgc-msl-uniform path=global.z offset=16 slots=1 type=float wire=float4")
require_record("${text}" "cgc-msl-uniform path=z offset=32 slots=1 type=float wire=float4")
if(text MATCHES "path=global.unused")
    message(FATAL_ERROR "Unreachable helper retained an unused global")
endif()
read_case(metadata_resources_a text)
require_record("${text}" "cgc-msl-resource path=fixedSlot texture=0 sampler=0 type=2d")
require_record("${text}" "cgc-msl-resource path=a texture=1 sampler=1 type=cube")
require_record("${text}" "cgc-msl-resource path=z texture=2 sampler=2 type=2d")
if(text MATCHES "cgc-msl-buffer")
    message(FATAL_ERROR "Resource-only shader emitted an empty numeric buffer")
endif()
read_case(metadata_attributes_a text)
require_record("${text}" "cgc-msl-attribute semantic=ATTRIB0 index=0 type=float4")
require_record("${text}" "cgc-msl-attribute semantic=NORMAL0 index=1 type=float4")
require_record("${text}" "cgc-msl-attribute semantic=POSITION0 index=2 type=float4")
read_case(metadata_nested text)
require_record("${text}" "cgc-msl-buffer index=0 bytes=112 alignment=16")
require_record("${text}" "cgc-msl-uniform path=data.inner[0].flags offset=0 slots=1 type=bool2 wire=uint4")
require_record("${text}" "cgc-msl-uniform path=data.inner[1].flags offset=32 slots=1 type=bool2 wire=uint4")
require_record("${text}" "cgc-msl-uniform path=data.inner[1].tint offset=48 slots=1 type=float2 wire=float4 source_type=half2")
require_record("${text}" "cgc-msl-uniform path=data.matrix offset=64 slots=3 type=float3x3 wire=float4 column_stride=16")
read_case(metadata_defaults text)
require_record("${text}" "cgc-msl-default path=b values=true")
require_record("${text}" "cgc-msl-default path=h values=5.000000000e-01,2.500000000e-01")
require_record("${text}" "cgc-msl-default path=u values=4294967295u")
require_record("${text}" "cgc-msl-default path=v values=1.000000015e-01")
file(READ "${BASE_DIR}/varying_fragment/shader.metal" text)
require_record("${text}" "cgc-msl-varying semantic=TEXCOORD2 field=cg_TEXCOORD2 type=int interpolation=flat")
