file(STRINGS "${MANIFEST}" rows)
list(POP_FRONT rows header)
if(NOT header STREQUAL "id,classification,test,source")
    message(FATAL_ERROR "unexpected Cg 2.0 manifest header: ${header}")
endif()
foreach(row IN LISTS rows)
    if(NOT row MATCHES "^[A-Z0-9_-]+,(valid-generic|invalid-language|backend-reject|out-of-scope),[^,]+,[^,]+$")
        message(FATAL_ERROR "malformed Cg 2.0 manifest row: ${row}")
    endif()
endforeach()
