file(MAKE_DIRECTORY "${WORK_DIR}")
foreach(nocode "" -nocode)
    foreach(seed FALSE TRUE)
        set(output "${WORK_DIR}/sentinel.metal")
        file(REMOVE "${output}")
        if(seed)
            file(WRITE "${output}" "KEEP_EXISTING_OUTPUT")
        endif()
        execute_process(COMMAND "${CGC}" -quiet -version 2.0 -profile mslv
            ${nocode} -o "${output}" "${SOURCE}"
            RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
        if("${status}" STREQUAL "0" OR NOT "${out}${err}" MATCHES "C6601")
            message(FATAL_ERROR "Missing expected type rejection: ${status} ${out}${err}")
        endif()
        if(seed)
            file(READ "${output}" contents)
            if(NOT contents STREQUAL "KEEP_EXISTING_OUTPUT")
                message(FATAL_ERROR "Existing output was overwritten")
            endif()
        elseif(EXISTS "${output}")
            message(FATAL_ERROR "Failed output was installed")
        endif()
        file(GLOB leaked "${WORK_DIR}/*.cgc-tmp-*")
        if(leaked)
            message(FATAL_ERROR "Leaked output transaction")
        endif()
    endforeach()
endforeach()
execute_process(COMMAND "${CGC}" -quiet -version 2.0 -profile mslv "${SOURCE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if("${status}" STREQUAL "0" OR "${out}" MATCHES "cgc-msl|metal_stdlib")
    message(FATAL_ERROR "Rejected stdout contains Metal output")
endif()
