file(READ "${BASE_DIR}/coverage-minimal_dependencies/shader.metal" source)
if(NOT source MATCHES "float cg_fn_no_global_[0-9]+\\(float cg_v_x_[0-9]+\\)" OR
   NOT source MATCHES "float cg_fn_only_a_[0-9]+\\(float cg_v_x_[0-9]+, float cg_v_a_[0-9]+\\)" OR
   NOT source MATCHES "float cg_fn_transitive_[0-9]+\\(float cg_v_x_[0-9]+, float cg_v_a_[0-9]+\\)")
    message(FATAL_ERROR "Helper dependency signatures are not minimal and transitive")
endif()
file(READ "${BASE_DIR}/coverage-global_constants/shader.metal" source)
if(source MATCHES "cgc-msl-buffer|cgc-msl-uniform")
    message(FATAL_ERROR "Global constants consumed uniform buffer storage")
endif()
file(READ "${BASE_DIR}/coverage-aggregate_defaults/shader.metal" source)
foreach(record
    "// cgc-msl-default path=a values=5.000000000e+00,6.000000000e+00"
    "// cgc-msl-default path=r values=2.000000000e+00,3.000000000e+00,4.000000000e+00")
    string(FIND "${source}" "${record}\n" found)
    if(found LESS 0)
        message(FATAL_ERROR "Missing aggregate default metadata: ${record}")
    endif()
endforeach()
# The new capability must not change the generic profile's legacy acceptance.
file(MAKE_DIRECTORY "${WORK_DIR}")
foreach(spec "matrix|C1020" "logical|C1052" "struct|C1056")
    string(REPLACE "|" ";" parts "${spec}")
    list(GET parts 0 name)
    list(GET parts 1 expected)
    if(name STREQUAL "matrix")
        set(text "float4 main(void):COLOR0 { float2x2 a=float2x2(1,2,3,4); float2x2 b=a*a; return float4(b[0][0],0,0,1); }")
    elseif(name STREQUAL "logical")
        set(text "bool bump(inout int i) { i++; return true; } float4 main(void):COLOR0 { int i=0; bool b=false && bump(i); return float4(i,0,0,1); }")
    else()
        set(text "struct R { float v; }; float4 main(void):COLOR0 { R r={2}; return float4(r.v,0,0,1); }")
    endif()
    file(WRITE "${WORK_DIR}/${name}.cg" "${text}\n")
    execute_process(COMMAND "${CGC}" -quiet -version 2.0 -profile generic -nocode "${WORK_DIR}/${name}.cg"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if("${status}" STREQUAL "0" OR NOT "${out}${err}" MATCHES "${expected}")
        message(FATAL_ERROR "Generic capability changed for ${name}: ${out}${err}")
    endif()
endforeach()
