function(hlsl_normalize_semantic input semantic_output direction_output)
    set(value "${input}")
    string(STRIP "${value}" value)
    set(direction "")
    if(value MATCHES "^\\$vin\\.(.+)$")
        set(direction in)
        set(value "${CMAKE_MATCH_1}")
    elseif(value MATCHES "^\\$vout\\.(.+)$")
        set(direction out)
        set(value "${CMAKE_MATCH_1}")
    endif()
    string(TOUPPER "${value}" value)
    if(value STREQUAL "POSITION" OR value STREQUAL "HPOS")
        set(value POSITION0)
    elseif(value STREQUAL "COLOR" OR value STREQUAL "COL")
        set(value COLOR0)
    elseif(value MATCHES "^COL([0-9]+)$")
        set(value "COLOR${CMAKE_MATCH_1}")
    elseif(value STREQUAL "TEXCOORD")
        set(value TEXCOORD0)
    elseif(value MATCHES "^TEX([0-9]+)$")
        set(value "TEXCOORD${CMAKE_MATCH_1}")
    endif()
    set(${semantic_output} "${value}" PARENT_SCOPE)
    set(${direction_output} "${direction}" PARENT_SCOPE)
endfunction()

function(hlsl_normalize_defaults input output)
    set(value "${input}")
    string(REGEX REPLACE "[=,{}()]" " " value "${value}")
    string(REGEX REPLACE "[ \t]+" ";" parts "${value}")
    set(cleaned "")
    foreach(part ${parts})
        if(part STREQUAL "")
            continue()
        endif()
        if(part MATCHES "^-?[0-9]+\\.[0-9]+$")
            string(REGEX REPLACE "0+$" "" part "${part}")
            if(part MATCHES "\\.$")
                string(REGEX REPLACE "\\.$" "" part "${part}")
            endif()
        endif()
        list(APPEND cleaned "${part}")
    endforeach()
    string(JOIN " " value ${cleaned})
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(hlsl_read_public_records path output)
    file(READ "${path}" raw)
    string(REPLACE "\r\n" "\n" raw "${raw}")
    string(REGEX MATCHALL "(^|\n)//[ ]*(var|default|cgc-default|cgc-bind interface)[^\n]*"
           lines "${raw}")
    set(records "")
    foreach(line ${lines})
        string(STRIP "${line}" line)
        if(line MATCHES "^//[ ]*cgc-bind interface +(in|out) +([^ ]+) +(.+) +([^ ]+)$")
            set(direction "${CMAKE_MATCH_1}")
            set(public_name "${CMAKE_MATCH_2}")
            set(type_name "${CMAKE_MATCH_3}")
            hlsl_normalize_semantic("${CMAKE_MATCH_4}" semantic ignored)
            if(public_name STREQUAL "result")
                set(public_name "$result")
            endif()
            string(STRIP "${type_name}" type_name)
            string(REGEX REPLACE "[ \t]+" " " type_name "${type_name}")
            list(APPEND records
                "semantic|${direction}|${public_name}|${type_name}|${semantic}")
        elseif(line MATCHES "^//[ ]*var +([^:]+):([^:]*):([^:]*):")
            set(type_and_public "${CMAKE_MATCH_1}")
            set(public_semantic "${CMAKE_MATCH_2}")
            set(register_name "${CMAKE_MATCH_3}")
            string(STRIP "${type_and_public}" type_and_public)
            string(REGEX MATCH "^(.+) +([^ ]+)$" split "${type_and_public}")
            set(type_name "${CMAKE_MATCH_1}")
            set(public_name "${CMAKE_MATCH_2}")
            string(REGEX REPLACE "^main\\." "" public_name
                   "${public_name}")
            string(STRIP "${type_name}" type_name)
            string(REGEX REPLACE "[ \t]+" " " type_name "${type_name}")
            string(STRIP "${register_name}" register_name)
            if(register_name MATCHES "^([cibs])\\[([0-9]+)\\]$")
                list(APPEND records
                    "register|${public_name}|${type_name}|${CMAKE_MATCH_1}${CMAKE_MATCH_2}")
            endif()
            string(STRIP "${public_semantic}" public_semantic)
            string(TOUPPER "${public_semantic}" binding_semantic)
            if(binding_semantic MATCHES "^([CIBS])([0-9]+)$")
                string(TOLOWER "${CMAKE_MATCH_1}" register_bank)
                list(APPEND records
                    "register|${public_name}|${type_name}|${register_bank}${CMAKE_MATCH_2}")
            elseif(binding_semantic MATCHES "^TEXUNIT([0-9]+)$")
                list(APPEND records
                    "register|${public_name}|${type_name}|s${CMAKE_MATCH_1}")
            elseif(NOT public_semantic STREQUAL "")
                hlsl_normalize_semantic("${public_semantic}"
                                        semantic direction)
                if(direction STREQUAL "")
                    message(FATAL_ERROR
                        "oracle semantic lacks $vin/$vout direction: ${line}")
                endif()
                if(public_name STREQUAL "main")
                    set(public_name "$result")
                endif()
                list(APPEND records
                    "semantic|${direction}|${public_name}|${type_name}|${semantic}")
            endif()
        elseif(line MATCHES "^//[ ]*(cgc-default|default) +(.+)$")
            hlsl_normalize_defaults("${CMAKE_MATCH_2}" default_record)
            list(APPEND records "default|${default_record}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES records)
    list(SORT records)
    set(${output} "${records}" PARENT_SCOPE)
endfunction()
