# Strict standalone target qualification, independent of a cgc Metal backend.
if(NOT APPLE AND NOT CMAKE_HOST_APPLE)
    message(FATAL_ERROR "Metal probes require macOS")
endif()
if(NOT DEFINED OUTPUT_DIR OR "${OUTPUT_DIR}" STREQUAL "")
    message(FATAL_ERROR "OUTPUT_DIR is required")
endif()
if(NOT DEFINED MSL_STANDARD)
    # Qualified with Apple metal 32023.883; retain the fixed 2.0 target.
    set(MSL_STANDARD macos-metal2.0)
endif()
if(NOT MSL_STANDARD MATCHES "^(metal2[.]0|macos-metal2[.]0)$")
    message(FATAL_ERROR "An explicit MSL 2.0 standard is required")
endif()
find_program(XCRUN xcrun REQUIRED)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
foreach(probe interface resources invalid)
    set(air "${OUTPUT_DIR}/${probe}.air")
    set(library "${OUTPUT_DIR}/${probe}.metallib")
    file(REMOVE "${air}" "${library}")
    execute_process(COMMAND "${XCRUN}" --sdk macosx metal
        "-std=${MSL_STANDARD}" -mmacosx-version-min=13.0
        -c "${CMAKE_CURRENT_LIST_DIR}/msl/probes/${probe}.metal" -o "${air}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(WRITE "${OUTPUT_DIR}/${probe}.compile.log" "${status}\n${out}${err}")
    if(probe STREQUAL "invalid")
        if("${status}" STREQUAL "0" OR NOT "${out}${err}" MATCHES "Deliberately invalid Metal qualification probe")
            message(FATAL_ERROR "Invalid probe did not fail for the expected reason: ${out}${err}")
        endif()
        continue()
    endif()
    if(NOT "${status}" STREQUAL "0" OR NOT EXISTS "${air}")
        message(FATAL_ERROR "${probe} compilation failed (${status}): ${out}${err}")
    endif()
    file(SIZE "${air}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Empty AIR for ${probe}")
    endif()
    execute_process(COMMAND "${XCRUN}" --sdk macosx metallib "${air}" -o "${library}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(WRITE "${OUTPUT_DIR}/${probe}.link.log" "${status}\n${out}${err}")
    if(NOT "${status}" STREQUAL "0" OR NOT EXISTS "${library}")
        message(FATAL_ERROR "${probe} linking failed (${status}): ${out}${err}")
    endif()
    file(SIZE "${library}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Empty metallib for ${probe}")
    endif()
endforeach()
message(STATUS "MSL 2.0 / macOS 13 syntax probes passed; GPU execution is not tested")
