foreach(arg CGC PROFILE SOURCE WORK_DIR)
    if(NOT DEFINED ${arg} OR "${${arg}}" STREQUAL "")
        message(FATAL_ERROR "${arg} is required")
    endif()
endforeach()
if(NOT DEFINED ENTRY)
    set(ENTRY main)
endif()
if(NOT DEFINED VERSION)
    set(VERSION 2.0)
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")
set(output "${WORK_DIR}/shader.metal")
file(REMOVE "${output}")
execute_process(COMMAND "${CGC}" -quiet -version "${VERSION}" -profile "${PROFILE}"
    -entry "${ENTRY}" -o "${output}" ${EXTRA_ARGS} "${SOURCE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
file(WRITE "${WORK_DIR}/cgc.log" "${status}\n${stdout}${stderr}")
if(DEFINED REJECT)
    if("${status}" STREQUAL "0" OR NOT "${stdout}${stderr}" MATCHES "${REJECT}" OR EXISTS "${output}")
        message(FATAL_ERROR "Expected rejection ${REJECT}: ${status}\n${stdout}${stderr}")
    endif()
    return()
endif()
if(NOT "${status}" STREQUAL "0" OR NOT EXISTS "${output}")
    message(FATAL_ERROR "cgc failed: ${status}\n${stdout}${stderr}")
endif()
file(READ "${output}" actual)
if(DEFINED EXPECTED)
    file(READ "${EXPECTED}" expected)
    string(REPLACE "\r\n" "\n" actual "${actual}")
    string(REPLACE "\r\n" "\n" expected "${expected}")
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "Generated Metal differs from ${EXPECTED}")
    endif()
endif()
if(REPEAT_OUTPUT)
    set(repeated "${WORK_DIR}/repeated.metal")
    execute_process(COMMAND "${CGC}" -quiet -version "${VERSION}" -profile "${PROFILE}"
        -entry "${ENTRY}" -o "${repeated}" "${SOURCE}"
        RESULT_VARIABLE repeat_status OUTPUT_VARIABLE repeat_out ERROR_VARIABLE repeat_err)
    if(NOT "${repeat_status}" STREQUAL "0" OR NOT EXISTS "${repeated}")
        message(FATAL_ERROR "Repeated compilation failed: ${repeat_out}${repeat_err}")
    endif()
    file(READ "${repeated}" repeat_contents)
    if(NOT "${actual}" STREQUAL "${repeat_contents}")
        message(FATAL_ERROR "Metal output is nondeterministic")
    endif()
endif()
if(APPLE_VALIDATE)
    set(SOURCE "${output}")
    include("${CMAKE_CURRENT_LIST_DIR}/validate_msl.cmake")
endif()
