foreach(arg SOURCE WORK_DIR)
    if(NOT DEFINED ${arg} OR "${${arg}}" STREQUAL "")
        message(FATAL_ERROR "${arg} is required")
    endif()
endforeach()
if(NOT DEFINED MSL_STANDARD)
    set(MSL_STANDARD macos-metal2.0)
endif()
if(NOT MSL_STANDARD MATCHES "^(macos-metal2[.]0|metal2[.]0)$")
    message(FATAL_ERROR "An explicit MSL 2.0 standard is required")
endif()
find_program(XCRUN xcrun REQUIRED)
file(MAKE_DIRECTORY "${WORK_DIR}")
set(air "${WORK_DIR}/shader.air")
set(library "${WORK_DIR}/shader.metallib")
file(REMOVE "${air}" "${library}")
execute_process(COMMAND "${XCRUN}" --sdk macosx metal
    "-std=${MSL_STANDARD}" -mmacosx-version-min=13.0 -c "${SOURCE}" -o "${air}"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
file(WRITE "${WORK_DIR}/compile.log" "${status}\n${out}${err}")
if(NOT "${status}" STREQUAL "0" OR NOT EXISTS "${air}")
    message(FATAL_ERROR "Apple compilation failed: ${status}\n${out}${err}")
endif()
file(SIZE "${air}" size)
if(size EQUAL 0)
    message(FATAL_ERROR "Apple compiler produced empty AIR")
endif()
execute_process(COMMAND "${XCRUN}" --sdk macosx metallib "${air}" -o "${library}"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
file(WRITE "${WORK_DIR}/link.log" "${status}\n${out}${err}")
if(NOT "${status}" STREQUAL "0" OR NOT EXISTS "${library}")
    message(FATAL_ERROR "Apple linking failed: ${status}\n${out}${err}")
endif()
file(SIZE "${library}" size)
if(size EQUAL 0)
    message(FATAL_ERROR "Apple linker produced empty library")
endif()
