struct DecoyOut {
    float4 position : POSITION;
    int vertexId : VERTEXID;
};

DecoyOut decoy_vertex(float4 position : POSITION,
                      int vertexId : VERTEXID)
{
    DecoyOut result;
    result.position = position;
    result.vertexId = vertexId;
    return result;
}

POINT POINT_OUT void main(
    AttribArray<float4> position : POSITION,
    AttribArray<int> vertexId : VERTEXID)
{
    return;
}
