struct FragmentOut {
    float4 color : COLOR0;
    float depth : DEPTH;
};

FragmentOut makeOutput(float4 color, inout float state)
{
    FragmentOut output;
    state = state + 0.25;
    output.color = color * state;
    output.depth = state;
    return output;
}

FragmentOut main(float4 color : TEXCOORD0)
{
    float state;
    if (color.x > 0.5) {
        state = 0.25;
        return makeOutput(color, state);
    }
    state = 0.5;
    return makeOutput(color, state);
}
