float4 main(float4 color : COLOR0,
            uniform sampler2D image0,
            uniform sampler2D image1,
            uniform sampler2D image2,
            uniform sampler2D image3,
            uniform sampler2D image4,
            uniform sampler2D image5,
            uniform sampler2D image6,
            uniform sampler2D image7,
            uniform sampler2D image8,
            uniform sampler2D image9,
            uniform sampler2D image10,
            uniform sampler2D image11,
            uniform sampler2D image12,
            uniform sampler2D image13,
            uniform sampler2D image14,
            uniform sampler2D image15,
            uniform sampler2D image16) : COLOR0
{
    float2 coord = color.xy;
    return color + tex2D(image0, coord) + tex2D(image1, coord) +
           tex2D(image2, coord) + tex2D(image3, coord) +
           tex2D(image4, coord) + tex2D(image5, coord) +
           tex2D(image6, coord) + tex2D(image7, coord) +
           tex2D(image8, coord) + tex2D(image9, coord) +
           tex2D(image10, coord) + tex2D(image11, coord) +
           tex2D(image12, coord) + tex2D(image13, coord) +
           tex2D(image14, coord) + tex2D(image15, coord) +
           tex2D(image16, coord);
}
