float4 main(float4 position : POSITION,
            float4 tex0 : TEXCOORD0,
            float4 tex1 : TEXCOORD1,
            float4 tex2 : TEXCOORD2,
            float4 tex3 : TEXCOORD3,
            float4 tex4 : TEXCOORD4,
            float4 tex5 : TEXCOORD5,
            float4 tex6 : TEXCOORD6,
            float4 tex7 : TEXCOORD7,
            float4 tex8 : TEXCOORD8,
            float4 tex9 : TEXCOORD9,
            float4 tex10 : TEXCOORD10,
            float4 tex11 : TEXCOORD11,
            float4 tex12 : TEXCOORD12,
            float4 tex13 : TEXCOORD13,
            float4 tex14 : TEXCOORD14) : POSITION
{
    return position + tex0 + tex1 + tex2 + tex3 + tex4 + tex5 + tex6 +
           tex7 + tex8 + tex9 + tex10 + tex11 + tex12 + tex13 + tex14;
}
