float4 main(float4 p : POSITION,
            float4 c0 : COLOR0,
            float4 t0 : TEXCOORD0,
            float4 t1 : TEXCOORD1,
            float4 t2 : TEXCOORD2,
            float4 t3 : TEXCOORD3,
            float4 t4 : TEXCOORD4,
            float4 t5 : TEXCOORD5,
            float4 t6 : TEXCOORD6,
            float4 t7 : TEXCOORD7) : COLOR
{
    return p + c0 + t0 + t1 + t2 + t3 + t4 + t5 + t6 + t7;
}
