float4 main(float2 t : TEXCOORD0,
            uniform sampler2D image : TEXUNIT0) : COLOR
{
    return tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t) + tex2D(image, t);
}
