struct Leaf {
    float4 value;
};

struct ResourceBlock {
    Leaf leaves[128];
    float extra;
};

struct VertexOut {
    float4 position : POSITION;
};

uniform ResourceBlock resources;

VertexOut main(float4 position : ATTRIB0)
{
    VertexOut output;
    output.position = position + resources.leaves[0].value +
                      resources.leaves[127].value * resources.extra;
    return output;
}
