uniform float3x3 output = float3x3(1.0, 2.0, 3.0,
                                   4.0, 5.0, 6.0,
                                   7.0, 8.0, 9.0);

float3 use_global(float3 value)
{
    return mul(output, value);
}

struct VertexOut {
    float4 position : POSITION;
};

VertexOut main(float4 position : ATTRIB0,
               uniform float3x3 output =
                   float3x3(11.0, 12.0, 13.0,
                            14.0, 15.0, 16.0,
                            17.0, 18.0, 19.0))
{
    VertexOut result;
    result.position = position;
    result.position.xyz = mul(output, result.position.xyz) +
                          use_global(result.position.xyz);
    return result;
}
